stages:
  get_data:
    cmd: python get_data.py
    deps:
      - get_data.py
    outs:
      - wine_quality.csv
  training:
    cmd: python train.py
    deps:
      - train.py
      - wine_quality.csv
    


    

    


